name: Linting and Building
on: [pull_request, push]
jobs:
  test:
    runs-on: node:14-alpine
    steps:
      - run: yarn && yarn lint:check && yarn build:check
      - run: echo "ğŸ This job's status is ${{ job.status }}."